[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "crypto-dashboard-modular"
version = "2.0.0"
description = "A modular crypto dashboard for tracking metrics and analyzing portfolios"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
authors = [
    {name = "Your Name", email = "your.email@example.com"},
]
keywords = ["crypto", "dashboard", "trading", "metrics", "binance"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Financial and Insurance Industry",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Office/Business :: Financial :: Investment",
]

dependencies = [
    "streamlit>=1.28.0",
    "pandas>=1.5.0",
    "numpy>=1.24.0",
    "requests>=2.28.0",
    "pyyaml>=6.0",
    "pyarrow>=10.0.0",
    "plotly>=5.14.0",
    "python-dateutil>=2.8.0",
    "pytz>=2023.3",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "pytest-cov>=4.0",
    "black>=22.0",
    "flake8>=5.0",
    "mypy>=1.0",
    "isort>=5.0",
]

[project.scripts]
crypto-dashboard = "crypto_dashboard_modular.main:main"

[project.urls]
Homepage = "https://github.com/yourusername/crypto-dashboard-modular"
Issues = "https://github.com/yourusername/crypto-dashboard-modular/issues"

[tool.setuptools]
packages = ["crypto_dashboard_modular"]
package-dir = {"crypto_dashboard_modular" = "."}

[tool.setuptools.package-data]
crypto_dashboard_modular = [
    "*.json",
    "*.yaml",
    "*.yml",
]

[tool.black]
line-length = 100
target-version = ['py38']
include = '\.pyi?$'

[tool.isort]
profile = "black"
line_length = 100

[tool.mypy]
python_version = "3.8"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = false
ignore_missing_imports = true